language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/coffee-print/coffee-print-docker
  DEPLOY_PATH: /root/coffee-print/coffee-print-account-server
  DOCKER_APP_PATH: app
  SERVICE_NAME: coffee-print

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_80743bc1ddd3_key -iv $encrypted_80743bc1ddd3_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: true

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    ssh root@$SSH_HOST "systemctl stop $SERVICE_NAME
      && mkdir $DEPLOY_PATH"
      '
  on:
    branch: master
